spring:
  application:
    name: springai.openai.mcp.client.filesystem

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano

    mcp:
      client:
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:mcp-servers.json
