spring:
  application:
    name: springai.openai.basic.chat

  threads:
    virtual:
      enabled: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1-nano

  docker:
    compose:
      lifecycle-management: start-and-stop
      stop:
        command: down
        timeout: 1m

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
