spring:
  application:
    name: springai.openai.chat.in.memory

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: always

  docker:
    compose:
      lifecycle-management: start-and-stop
      stop:
        command: down
        timeout: 1m